name: farm_thoughts_web_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  go_router: ^16.1.0
  flutter_svg: ^2.2.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: "assets/fonts/Poppins-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Poppins-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Poppins-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Poppins-ExtraBold.ttf"
          weight: 800





